snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn:
                - redis://redis-sentinel1:5000
            options:
                replication: sentinel
                service: mymaster
                parameters:
                    database: 1
            logging: false
# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: phpredis
#            alias: default
#            dsn: "%env(REDIS_URL)%"
