services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ./:/usr/src/app

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 4601:80
    depends_on:
      - php-fpm

  redis-master:
    container_name: "redis-master"
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis.conf/redis.conf:/usr/local/etc/redis/redis.conf:rw"

  redis-slave1:
    container_name: "redis-slave1"
    image: redis:latest
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379

  redis-slave2:
    container_name: "redis-slave2"
    image: redis:latest
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379

  redis-sentinel1:
    container_name: 'redis-sentinel1'
    image: redis:latest
    ports:
      - "5000:5000"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./docker/redis/sentinel/sentinel.conf:/etc/sentinel.conf:rw,Z"